trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseNode@1
    inputs:
      version: '16.x'
    displayName: 'Use Node.js 16.x'
    
  - script: |
      npm install
    displayName: 'Install dependencies'
  
  - script: |
      npm test
    displayName: 'Run tests'